<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\..\src\ZHSan.Editor.Infrastructure\ZHSan.Editor.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ZHSan.Editor.Desktop\ZHSan.Editor.Desktop.csproj" />
    <Reference Include="ZHSan.Data">
      <HintPath>..\..\libs\ZHSan.Data.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
