<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\ZHSan.Editor.Application\ZHSan.Editor.Application.csproj" />
    <ProjectReference Include="..\ZHSan.Editor.Infrastructure\ZHSan.Editor.Infrastructure.csproj" />
  </ItemGroup>
</Project>
